name: lessons_chat
description: A new Flutter project.


publish_to: 'none'

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  #firebase
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  
  assets:
   - images/


  